spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9200
      cluster-name: emsdb-local
  application:
    name: ems
  jackson:
    serialization:
      fail-on-empty-beans: false
#  security:
#    user:
#      password: aliassad
#      name: ali
  jpa:
    open-in-view: true
    properties:
      show_sql: true
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      #      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
#      hibernate.cache.factory_class: org.redisson.hibernate.RedissonRegionFactory
#      hibernate.cache.redisson.fallback: true
#      hibernate.cache.redisson.config: redission/redisson-dev.yaml
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      #      hibernate.enable_lazy_load_no_trans: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ems?createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  main:
    allow-circular-references: true

    allow-bean-definition-overriding: true
#  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379
#  elasticsearch:
#    uris: http://localhost:9200
server:
  port: 9191

logging:
  level:
    com.ems.EmployeeManagementService: Debug
management:
  health:
    elasticsearch:
      enabled: false



jwt_secret : tabadul
jwtExpirationMs: 120000
refreshTokenDurationMs: 1200000
springdoc:
  swagger-ui:
    csrf:
      enabled: true
